---
version: '3'

services:
  drupal:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      # The virtual host is used when we want to access our site via an
      # Nginx Proxy locally; and is required by the script
      # ./scripts/https-deploy.sh.
      # See https://blog.dcycle.com/blog/2018-10-27 for details.
      - VIRTUAL_HOST=${VIRTUAL_HOST}
    volumes:
      - "./do-not-commit/legacy-files:/legacy-files"
      - "./drupal/custom-modules:/var/www/html/modules/custom"
      - "./drupal/custom-themes:/var/www/html/themes/custom"
      - "drupal-files:/var/www/html/sites/default/files:rw"
      - "./drupal/config:/var/www/config"
      - "./drupal/scripts:/scripts"
      - "./do-not-commit/log:/var/log"
    ports:
      - "80"
    links:
      - mysql:mysql
    working_dir: /var/www/html

  # Database server
  mysql:
    image: mysql:5
    environment:
      MYSQL_DATABASE: drupal
      MYSQL_ROOT_PASSWORD: drupal
      MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
    volumes:
      - "mysql:/var/lib/mysql"
      - ./mysql/cnf:/etc/mysql/conf.d

# Specifying the network name makes it predictable on all environments,
# for example when running ./scripts/migrate-all.sh, or when running browser
# tests on a CI environment, or any other tasks which requires external
# docker containers to connect to our network.
# This network (tdj_d8) has been previously created in
# ./scripts/deploy.sh
# See https://github.com/docker/compose/issues/3736.
networks:
  default:
    external:
      name: tdj_d8

volumes:
  mysql:
  drupal-files:
